### ISSUE TITLE
# 49 Fix backend layout:

### ISSUE THREAD

**Issue by alessiavozzo** [Arianna-Salvini/laravel-bool-bnb#99]
-Registration form must have a disclaimer saying that all fields are mandatory
-Comment away search button in dashboard
-Change input fields color in forms
-Change details show page: services must have a better appearence
-Change tab title from Laravel to AdminBoolBNB
-Add not-available default picture when no image has been uploaded
-Title must appear even if there's no pic available

**Comment by Kasketto001** [comment]
✨
